const Virtual = require("sools/virtualizing/Virtual");
const Data =  require("sools/data")
const Model = require("sools/data/Model");
const Object = require("sools/data/Object");
const constantes = require("./constantes")
module.exports = Data.define({
	position:{
		extends:Object,
		properties:{
			x:'number',
			y:'number'
		}
	},
	map:{
		extends:Model,
		properties:{
			_id:'string',
			name:'string',
			ressources:['ressource']
		}
	},
	ressource:{
		extends:Model,
		properties:{
			_id:'string',
			level:'number',
			type:'string',
			map:'map',
			position:'position'
		}
	},
	user:{
		extends:Model,
		properties:{
			_id:'string',
			name:'string',
			email:'string',
			password:'string',
			memberships:['membership']
		},
		indexes:[{
			type:'unique',
			properties:['_id']
		},{
			type:'unique',
			properties:['name']
		},{
			type:'unique',
			properties:['email']
		}],
	},
	group:{
		extends:Model,
		properties:{
			_id:'string',
			name:'string',
			memberships:['membership']
		},
		indexes:[{
			type:'unique',
			properties:['_id']
		},{
			type:'unique',
			properties:['name']
		}],
	},
	membership:{
		extends:Model,
		properties:{
			_id:'string',
			user:'user',
			group:'group'
		},
		indexes:[{
			type:'unique',
			properties:['_id']
		},
		{
			type:'unique',
			properties:['user','group']
		}]
	}	
})